### ISSUE TITLE
CSV difference ORIG-SIMPL

### ISSUE THREAD

**Issue by Radiation-Transport** [Fusion4Energy/SCtools#1]
The difference sometimes is not properly computed.
<img width="140" alt="2020-06-02 16_01_47-UCTS_SHROUD_TYPE_D csv - Excel" src="https://user-images.githubusercontent.com/48320561/83529257-6579b900-a4ea-11ea-80b8-384ff03ba872.png">

**Comment by AlvaroCubi** [comment]
Closing the issue as this was bug was found on an earlier version of the script with a different implementation. Please reopen the issue if the bug is found again.
